let print


func (val) {
  try {
    throw null
  } catch(ex) {
    return val;
  }
}
